class_list = []
name=input("what is your name ")
class_list.append(name)
name_1=input("what is your class mate name ")
class_list.append(name_1)
name_2=input("what is your class mate name ")
class_list.append(name_2)
name_3=input("what is your class mate name ")
class_list.append(name_3)
name_4=input("what is your class mate name ")
class_list.append(name_4)
print("this is who is in your class")
print(class_list)
print("your mate leaves the class this is who is in your class now")
class_list.remove(name_4)
print(class_list)
print("this is class list")
for name in class_list:
    print(name)